### ISSUE TITLE
Effet de bord de l'activation du focus sur un élément de la marque blanche

### ISSUE THREAD

**Issue by spelhate** [megalis-bretagne/mq-actes#1]
Bonjour,
La Comme de Trans La Forêt nous signale un désagrément lié à l'intégration de l'iframe marque blanche dans une page de son site.
L'iframe est intégrée en bas de page, mais le focus activé par défaut pour la marque blanche fait que la page scrolle jusqu'à l'iframe.
Doit-on conserver ce comportement ?

**Comment by ElodieTessier** [comment]
Bonjour,
Je complète cette issue avec le lien vers le ticket JIRA : https://jira.megalis.bretagne.bzh/browse/PLTF-126003

**Comment by yguenneugues** [comment]
@spelhate Peux tu nous donner le lien vers la page qui affiche l'iframe sur le site de Trans La Forêt

**Comment by lvinsonneau** [comment]
Le lien a été corrigé sur Trans la Forêt, en inversant l'ordre.

**Comment by gautierrog** [comment]
J'ai poussé un fix de la marque blanche pour le souci de focus lorsqu'integré en iframe

**Comment by lvinsonneau** [comment]
suite discussion point suivi projet
